INSERT INTO tb_categoria (DESCRICAO, HORARIO_CRIADO) VALUES ('Livros', NOW());
INSERT INTO tb_categoria (DESCRICAO, HORARIO_CRIADO) VALUES ('Eletrônicos', NOW());
INSERT INTO tb_categoria (DESCRICAO, HORARIO_CRIADO) VALUES ('Computadores', NOW());
